name: Sync demo to template repo

on:
  push:
    branches:
      - main
      - beta
    paths:
      - 'demo/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup git identity
        run: |
          git config user.name "better-invite-bot[bot]"
          git config user.email "261293591+better-invite-bot[bot]@users.noreply.github.com"

      - name: Create subtree branch
        run: |
          git subtree split --prefix=demo -b demo-branch
        
      - name: Apply modifications
        run: |
          git checkout demo-branch

          # Update README

          # Update separate repository reference
          sed -i 's|> Better Invite Starter code is also available on a separate \[repository\](https://github.com/better-invite/better-invite-starter/tree/main)|> Better Invite Starter code is also available on the \[Better Invite monorepo\](https://github.com/better-invite/better-invite/tree/main/demo)\n\n> Please open any issues or pull requests on the \[Better Invite monorepo\](https://github.com/better-invite/better-invite)|' README.md
          
          # Update title
          perl -0777 -pe 's|<h1 align="center">\s*Better Invite Starter\s*</h1>|<h1 align="center">\n  Better Invite Starter Template\n</h1>|s' README.md > README.tmp && mv README.tmp README.md

          # Create .github files
          mkdir -p .github

          # Copy files from monorepo
          git --work-tree=. checkout main -- .github/CODEOWNERS

          # Commit changes
          git add .
          git commit --amend --no-edit

      - name: Push to template repo
        run: |
          git remote add template https://x-access-token:${{ secrets.TEMPLATE_REPO_TOKEN }}@github.com/better-invite/better-invite-starter.git
          git push template demo-branch:${{ github.ref_name }} --force