name: Sync demo to template repo

on:
  push:
    branches:
      - main
      - beta
    paths:
      - 'demo/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup git identity
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create subtree branch
        run: |
          git subtree split --prefix=demo -b demo-branch
      
      - name: Update README link
        run: |
          git checkout demo-branch

          sed -i 's|> Better Invite Starter code is also available a separate \[repository\](https://github.com/better-invite/better-invite-starter/tree/main)|> Better Invite Starter code is also available on the \[Better Invite monorepo\](https://github.com/better-invite/better-invite/tree/main/demo)|' README.md

          git add README.md
          git commit --amend --no-edit

      - name: Push to template repo (same branch)
        run: |
          git remote add template https://x-access-token:${{ secrets.TEMPLATE_REPO_TOKEN }}@github.com/better-invite/better-invite-starter.git
          git push template demo-branch:${{ github.ref_name }} --force